ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/Customer/DeleteCustomer.cshtml.cs
using ITGuru.FourWheels.Service;
using ITGuru.FourWheels.Web.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITGuru.FourWheels.Web.Pages.Administration.Customer
{
    public class DeleteCustomerModel : PageModel
    {
        private readonly ICustomerService _customerService;
        public DeleteCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        [BindProperty]
        public CustomerDTO Customer { get; set; }

        public void OnGet(string CustomerId)
        {
            Customer = _customerService.GetById(new Guid(CustomerId)) as CustomerDTO;
        }

        public IActionResult OnPost()
        {
            if (_customerService.Remove(Customer).Succeeded)
            {
                TempData["Message"] = $"Successfully delete the customer {Customer.FirstName} {Customer.LastName}";
                TempData["MessageStatus"] = MessageStatus.Success;
                return RedirectToPage("/Administration/SearchPage");
            }
            else
            {
                TempData["Message"] = $"Couldn't delete customer {Customer.FirstName} {Customer.LastName}";
                TempData["MessageStatus"] = MessageStatus.Failed;
                return RedirectToPage("/Administration/SearchPage");
            }
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/Customer/UpdateCustomer.cshtml.cs
using ITGuru.FourWheels.Service;
using ITGuru.FourWheels.Web.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITGuru.FourWheels.Web.Pages.Administration.Customer
{
    public class UpdateCustomerModel : PageModel
    {
        public UpdateCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        private readonly ICustomerService _customerService;

        [BindProperty]
        public CustomerDTO Customer { get; set; }

        [BindProperty]
        public string Message { get; set; }
        [BindProperty]
        public MessageStatus MessageStatus { get; set; }

        public void OnGet(string CustomerId)
        {
            Customer = _customerService.GetById(new Guid(CustomerId)) as CustomerDTO;
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Customer != null)
                {
                    var result = _customerService.Update(Customer);
                    if (result.Succeeded)
                    {
                        Message = $"Successfully updated the customer: {Customer.FirstName} {Customer.LastName}";
                        MessageStatus = MessageStatus.Success;
                        TempData["Message"] = Message;
                        TempData["MessageStatus"] = MessageStatus;
                        return RedirectToPage("/Administration/SearchPage");
                    }
                    else
                    {
                        Message = $"Couldn't update the customer.";
                        MessageStatus = MessageStatus.Failed;
                        TempData["Message"] = Message;
                        TempData["MessageStatus"] = MessageStatus;
                        return RedirectToPage("/Administration/SearchPage");
                    }
                }
                return RedirectToPage("/Administration/SearchPage");
            }
            else
            {
                return Page();
            }
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/SearchPage.cshtml.cs
using ITGuru.FourWheels.Service;
using ITGuru.FourWheels.Web.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITGuru.FourWheels.Web.Pages.Administration
{
    public class SearchPageModel : PageModel
    {
        public SearchPageModel(ICustomerService customerService, IVehicleService vehicleService, ITaskService taskService)
        {
            _customerService = customerService;
            _vehicleService = vehicleService;
            _taskService = taskService;
        }

        private readonly ICustomerService _customerService;
        private readonly IVehicleService _vehicleService;
        private readonly ITaskService _taskService;

        [BindProperty]
        public IReadOnlyList<ICustomer> Customers { get; set; }

        [BindProperty]
        public CustomerDTO Customer { get; set; }
        [BindProperty]
        public VehicleDTO Vehicle { get; set; }
        [BindProperty]
        public TaskDTO Task { get; set; }

        [BindProperty]
        public string Message { get; set; }
        [BindProperty]
        public MessageStatus MessageStatus { get; set; }

        [BindProperty]
        public bool ShowTaskCreation { get; set; }

        public void OnGet()
        {
            Customers = _customerService.GetAll();
        }

        public IActionResult OnPostCreateCustomer()
        {
            if (ModelState.IsValid)
            {
                Customer.Id = Guid.NewGuid();
                Customer.Phone = Customer.Phone.Replace(" ", string.Empty);
                var customerResult = _customerService.Add(Customer);

                Vehicle.Id = Guid.NewGuid();
                Vehicle.CustomerId = Customer.Id;
                var vehicleResult = _vehicleService.Add(Vehicle);

                Task.Id = Guid.NewGuid();
                Task.OrderNumber = $"FW{Task.OrderNumber}";
                Task.AssociatedVehicleId = Vehicle.Id;
                Task.Notes = "";
                var taskResult = _taskService.Add(Task);
                if (customerResult.Succeeded && vehicleResult.Succeeded && taskResult.Succeeded)
                {
                    Message = $"Successfully created a new customer with a vehicle and a task!";
                    MessageStatus = MessageStatus.Success;
                    TempData["Message"] = Message;
                    TempData["MessageStatus"] = MessageStatus;
                    return RedirectToPage("/Administration/SearchPage");
                }
                else
                {
                    Message = $"There was a mistake trying to add a customer with their vehicle and a task.";
                    MessageStatus = MessageStatus.Failed;
                    TempData["Message"] = Message;
                    TempData["MessageStatus"] = MessageStatus;
                    return RedirectToPage("/Administration/SearchPage");
                }
            }
            else
            {
                Message = $"Validation on the inputs weren't acceptable!";
                MessageStatus = MessageStatus.Failed;
                TempData["Message"] = Message;
                TempData["MessageStatus"] = MessageStatus;
                OnGet();
                return Page();
            }
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/Tasks/DeleteTask.cshtml.cs
using ITGuru.FourWheels.Service;
using ITGuru.FourWheels.Web.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITGuru.FourWheels.Web.Pages.Administration.Tasks
{
    public class DeleteTaskModel : PageModel
    {
        private readonly ITaskService _taskService;
        public DeleteTaskModel(ITaskService taskService)
        {
            _taskService = taskService;
        }

        [BindProperty]
        public TaskDTO Task { get; set; }

        public void OnGet(string taskId)
        {
            Task = _taskService.GetById(new Guid(taskId)) as TaskDTO;
        }

        public IActionResult OnPost()
        {
            if (_taskService.Remove(Task).Succeeded)
            {
                TempData["Message"] = $"Successfully delete the task {Task.Description}";
                TempData["MessageStatus"] = MessageStatus.Success;
                return Redirect($"/Administration/Tasks/VehicleTasks/{Task.AssociatedVehicleId}");
            }
            else
            {
                TempData["Message"] = $"Couldn't delete task {Task.Description}";
                TempData["MessageStatus"] = MessageStatus.Failed;
                return Redirect($"/Administration/Tasks/VehicleTasks/{Task.AssociatedVehicleId}");
            }
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/Tasks/UpdateTask.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITGuru.FourWheels.Web.Pages.Administration.Tasks
{
    public class UpdateTaskModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/Tasks/VehicleTasks.cshtml.cs
using ITGuru.FourWheels.Service;
using ITGuru.FourWheels.Service.Repos;
using ITGuru.FourWheels.Web.Enums;
using ITGuru.FourWheels.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITGuru.FourWheels.Web.Pages.Administration.Tasks
{
    public class VehicleTasksModel : PageModel
    {
        public VehicleTasksModel(ITaskService taskService, IVehicleService vehicleService)
        {
            _taskService = taskService;
            _vehicleService = vehicleService;
        }

        private readonly IVehicleService _vehicleService;
        private readonly ITaskService _taskService;

        [BindProperty]
        public IReadOnlyList<ITask> Tasks { get; set; }

        [BindProperty]
        public VehicleTasksVM VehicleTasksVM { get; set; }

        [BindProperty]
        public string Message { get; set; }

        [BindProperty]
        public MessageStatus MessageStatus { get; set; }

        public void OnGet(string VehicleId)
        {
            VehicleTasksVM = new VehicleTasksVM();

            var vehicle = _vehicleService.GetById(new Guid(VehicleId)) as VehicleDTO;
            Tasks = vehicle.GetTasks();

            VehicleTasksVM.LicensePlate = vehicle.LicensePlate;
            VehicleTasksVM.Brand = vehicle.Brand;
            VehicleTasksVM.Model = vehicle.Model;
            VehicleTasksVM.VehicleId = vehicle.Id;
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                VehicleTasksVM.TaskId = Guid.NewGuid();

                var task = new TaskDTO()
                {
                    Id = VehicleTasksVM.TaskId,
                    AssociatedVehicleId = VehicleTasksVM.VehicleId,
                    OrderNumber = VehicleTasksVM.OrderNumber,
                    OrderDate = VehicleTasksVM.OrderDate,
                    Description = VehicleTasksVM.Description
                };
                var taskResult = _taskService.Add(task);
                if (taskResult.Succeeded)
                {
                    Message = $"Successfully created a new customer with a vehicle and a task!";
                    MessageStatus = MessageStatus.Success;
                    TempData["Message"] = Message;
                    TempData["MessageStatus"] = MessageStatus;
                    return RedirectToPage("/Administration/Tasks/VehicleTasks", VehicleTasksVM.VehicleId);
                }
                else
                {
                    Message = $"There was a mistake trying to add a customer with their vehicle and a task.";
                    MessageStatus = MessageStatus.Failed;
                    TempData["Message"] = Message;
                    TempData["MessageStatus"] = MessageStatus;
                    return RedirectToPage("/Administration/Tasks/VehicleTasks", VehicleTasksVM.VehicleId);
                }
            }
            else
            {
                Message = $"Validation on the inputs weren't acceptable!";
                MessageStatus = MessageStatus.Failed;
                TempData["Message"] = Message;
                TempData["MessageStatus"] = MessageStatus;
                OnGet(VehicleTasksVM.VehicleId.ToString());
                return Page();
            }
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/Vehicle/CustomerVehicles.cshtml.cs
using ITGuru.FourWheels.Data.DataModels;
using ITGuru.FourWheels.Service;
using ITGuru.FourWheels.Service.Repos;
using ITGuru.FourWheels.Web.Enums;
using ITGuru.FourWheels.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.WebSockets;

namespace ITGuru.FourWheels.Web.Pages.Administration.Vehicle
{
    public class CustomerVehiclesModel : PageModel
    {
        private readonly ICustomerService _customerService;
        private readonly IVehicleService _vehicleService;
        private readonly ITaskService _taskService;
        public CustomerVehiclesModel(ICustomerService customerService, IVehicleService vehicleService, ITaskService taskService)
        {
            _customerService = customerService;
            _vehicleService = vehicleService;
            _taskService = taskService;
        }

        [BindProperty]
        public IReadOnlyList<IVehicle> Vehicles { get; set; }

        [BindProperty]
        public CustomerVehiclesVM CustomerVehicle { get; set; }

        [BindProperty]
        public TaskDTO Task { get; set; }

        [BindProperty]
        public string Message { get; set; }
        [BindProperty]
        public MessageStatus MessageStatus { get; set; }

        public void OnGet(string CustomerId)
        {
            CustomerVehicle = new();

            var Customer = _customerService.GetById(new Guid(CustomerId)) as CustomerDTO;
            Vehicles = Customer.GetVehicles();

            CustomerVehicle.FirstName = Customer.FirstName;
            CustomerVehicle.LastName = Customer.LastName;
            CustomerVehicle.CustomerId = Customer.Id;
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                CustomerVehicle.VehicleId = Guid.NewGuid();
                VehicleDTO vehicle = new VehicleDTO
                {
                    Id = CustomerVehicle.VehicleId,
                    Brand = CustomerVehicle.Brand,
                    Model = CustomerVehicle.Model,
                    LicensePlate = CustomerVehicle.LicensePlate,
                    CustomerId = CustomerVehicle.CustomerId
                };
                var vehicleResult = _vehicleService.Add(vehicle);

                Task.Id = Guid.NewGuid();
                Task.OrderNumber = $"FW{Task.OrderNumber}";
                Task.AssociatedVehicleId = vehicle.Id;
                Task.Notes = "";
                var taskResult = _taskService.Add(Task);
                if (vehicleResult.Succeeded && taskResult.Succeeded)
                {
                    Message = vehicleResult.Message;
                    MessageStatus = MessageStatus.Success;
                    TempData["Message"] = Message;
                    TempData["MessageStatus"] = MessageStatus;
                    return RedirectToPage("/Administration/Vehicle/CustomerVehicles", CustomerVehicle.CustomerId);
                }
                else
                {
                    Message = vehicleResult.Message;
                    MessageStatus = MessageStatus.Failed;
                    TempData["Message"] = Message;
                    TempData["MessageStatus"] = MessageStatus;
                    return RedirectToPage("/Administration/Vehicle/CustomerVehicles", CustomerVehicle.CustomerId);
                }
            }
            else
            {
                Message = $"Validation on the inputs weren't acceptable!";
                MessageStatus = MessageStatus.Failed;
                TempData["Message"] = Message;
                TempData["MessageStatus"] = MessageStatus;
                OnGet(CustomerVehicle.CustomerId.ToString()); ;
                return Page();
            }
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/Vehicle/DeleteVehicle.cshtml.cs
using ITGuru.FourWheels.Service;
using ITGuru.FourWheels.Web.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ITGuru.FourWheels.Web.Pages.Administration.Vehicle
{
    public class DeleteVehicleModel : PageModel
    {
        private readonly IVehicleService _vehicleService;
        public DeleteVehicleModel(IVehicleService vehicleService)
        {
            _vehicleService = vehicleService;
        }

        [BindProperty]
        public VehicleDTO Vehicle { get; set; }

        public void OnGet(string vehicleId)
        {
            Vehicle = _vehicleService.GetById(new Guid(vehicleId)) as VehicleDTO;
        }

        public IActionResult OnPost()
        {
            if (_vehicleService.Remove(Vehicle).Succeeded)
            {
                TempData["Message"] = $"Successfully delete the vehicle {Vehicle.Brand} {Vehicle.Model}";
                TempData["MessageStatus"] = MessageStatus.Success;
                return Redirect($"/Administration/Vehicle/CustomerVehicles/{Vehicle.CustomerId}");
            }
            else
            {
                TempData["Message"] = $"Couldn't delete vehicle {Vehicle.Brand} {Vehicle.Model}";
                TempData["MessageStatus"] = MessageStatus.Failed;
                return Redirect($"/Administration/Vehicle/CustomerVehicles/{Vehicle.CustomerId}");
            }
        }
    }
}

ITGuru.FourWheels/ITGuru.FourWheels.Web/Pages/Administration/SearchPage.cshtml
@page
@model ITGuru.FourWheels.Web.Pages.Administration.SearchPageModel
@using ITGuru.FourWheels.Web.Enums;

<div>
    <div class="row mb-2">
        @if (TempData.Peek("Message") != null)
        {
            Model.Message = TempData["Message"].ToString();
            Model.MessageStatus = (MessageStatus)TempData["MessageStatus"];

            @if (Model.MessageStatus == MessageStatus.Success)
            {
                <div class="alert alert-success rounded col-md-12 text-center" role="alert" id="PopupBox">@Model.Message</div>
            }
            else if (Model.MessageStatus == MessageStatus.Failed)
            {
                <div class="alert alert-danger rounded col-md-12 text-center" role="alert" id="PopupBox">@Model.Message</div>
            }            
        }
    </div>
    <h3 class="text-center">List of Customers:</h3>
    <div class="row mb-2">
        <div class="col-10">
            <input class="form-control" type="text" id="SearchInput" onkeyup="Search()" placeholder="Search for names..">
        </div>
        <div class="col-2">
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#createCustomer"><i class="fa-solid fa-plus"></i> New customer</button>
        </div>
    </div>
    <div>
        <table class="table table-striped" id="SearchTable">
            <tr class="header">
                <th class="col-4">Name</th>
                <th class="col-2">Phone</th>
                <th class="col-4">Email</th>
                <th class="col-2">Options</th>
            </tr>
            @foreach (var customer in Model.Customers)
            {
                <tr>
                    <td><a asp-page="/Administration/Vehicle/CustomerVehicles" asp-route-CustomerId="@customer.Id">@customer.FirstName @customer.LastName</a></td>
                    <td>@customer.Phone</td>
                    <td>@customer.Email</td>
                    <td>
                        <div class="row">
                            <div class="col-6">
                                <a class="btn btn-warning" asp-page="/Administration/Customer/UpdateCustomer" asp-route-CustomerId="@customer.Id"><i class="fa-solid fa-pen-to-square"></i>Update</a>
                            </div>
                            <div class="col-6">
                                <a class="btn btn-danger" asp-page="/Administration/Customer/DeleteCustomer" asp-route-CustomerId="@customer.Id" ><i class="fa-solid fa-trash"></i>Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<!-- #region Modals -->
<form method="post" asp-page-handler="CreateCustomer" id="createForm">
    <div class="modal fade" id="createCustomer" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createCustomerLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <!-- Customer -->
                    <h5 class="modal-title" id="createCustomerLabel">Create a new Customer</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>First name:</label>
                        </div>
                        <div class="col-8">
                            <input class="form-control" asp-for="@Model.Customer.FirstName" type="text" placeholder="Enter customers first name..." />
                            <span class="text-danger" asp-validation-for="@Model.Customer.FirstName"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Last name:</label>
                        </div>
                        <div class="col-8">
                            <input class="form-control" asp-for="@Model.Customer.LastName" type="text" placeholder="Enter customers last name..." />
                            <span class="text-danger" asp-validation-for="@Model.Customer.LastName"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Phone:</label>
                        </div>
                        <div class="col-8">
                            <input class="form-control" asp-for="@Model.Customer.Phone" type="text" placeholder="Enter customers phone number..." />
                            <span class="text-danger" asp-validation-for="@Model.Customer.Phone"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Email:</label>
                        </div>
                        <div class="col-8">
                            <input class="form-control" asp-for="@Model.Customer.Email" type="text" placeholder="Enter customers email..." />
                            <span class="text-danger" asp-validation-for="@Model.Customer.Email"></span>
                        </div>
                    </div>
                    <!-- Vehicle -->
                    <h5 class="modal-title">Vehicle information:</h5>
                    <hr />
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>License plate:</label>
                        </div>
                        <div class="col-8">
                            <input class="form-control" asp-for="@Model.Vehicle.LicensePlate" type="text" placeholder="Enter vehicle's license plate..." />
                            <span class="text-danger" asp-validation-for="@Model.Vehicle.LicensePlate"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Brand:</label>
                        </div>
                        <div class="col-8">
                            <input class="form-control" asp-for="@Model.Vehicle.Brand" type="text" placeholder="Enter vehicle's brand..." />
                            <span class="text-danger" asp-validation-for="@Model.Vehicle.Brand"></span>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-4">
                            <label>Model:</label>
                        </div>
                        <div class="col-8">
                            <input class="form-control" asp-for="@Model.Vehicle.Model" type="text" placeholder="Enter vehicle's model..." />
                            <span class="text-danger" asp-validation-for="@Model.Vehicle.Model"></span>
                        </div>
                    </div>
                    <!-- Task -->                    
                    <div>
                        <h5 class="modal-title">Task information:</h5>
                        <hr />
                        <div class="row mb-2">
                            <div class="col-4">
                                <label>Order Number:</label>
                            </div>
                            <div class="col-1 pt-2 ps-4">
                                <span><b>FW</b></span>
                            </div>
                            <div class="col-7">                                
                                <input class="form-control" asp-for="@Model.Task.OrderNumber" type="text" placeholder="Enter Order number..." />
                                <span class="text-danger" asp-validation-for="@Model.Task.OrderNumber"></span>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4">
                                <label>Order Date:</label>
                            </div>
                            <div class="col-8">
                                <input type="datetime" class="form-control" asp-for="@Model.Task.OrderDate" type="text" value="@DateTime.Now" placeholder="@DateTime.Now" />
                                <span class="text-danger" asp-validation-for="@Model.Task.OrderDate"></span>
                            </div>
                        </div>
                        <div class="row mb-2">
                            <div class="col-4">
                                <label>Description:</label>
                            </div>
                            <div class="col-8">
                                <textarea class="form-control" asp-for="@Model.Task.Description" placeholder="Enter the task problem..." >

                                </textarea>
                                <span class="text-danger" asp-validation-for="@Model.Task.Description"></span>
                            </div>
                        </div>
                    </div>                    
                </div>
                <div class="modal-footer">                    
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success" id="btnCreate">Create</button>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- #endregion -->

@section Scripts{
    <script src="~/js/SearchPageScript.js"></script>
}